name: 035_phenobase
channels:
  - conda-forge
dependencies:
  - python=3.12
  - mypy
  - ruff
  - pytest
  - pytest-cov
  - pytest-integration
  - pip
  - python-dotenv
  - psycopg2
  - sqlalchemy
  - types-psycopg2
  - fastapi
  - uvicorn
  - httpx
  - mlflow
  - paramiko
  - types-paramiko
  - smbprotocol
  - rasterio 
  - planetary-computer
  - pystac-client 
  - numpy 
  - pip: 
  # pip-only packages go here if needed
