     name: 035_phenobase
     channels:
       - conda-forge
       - defaults
     dependencies:
       - python=3.12
       - autopep8
       - mypy
       - pylint
       - pytest
       - pytest-cov
       - pip
       - python-dotenv
       - psycopg2
       - types-psycopg2
       - sqlalchemy
       - pip:
         # pip-only packages go here if needed