[pytest]
markers =
    unit: Atomic Unit Tests
    integration: Integration Tests that interact with external systems 
    fola: Tests that only run in Fola Infrastructure (NAS, Gamarello, database server)