# Starts a Test Postgres Database for development and testing, if  dedicated machine with real postgres access is not available
services:
  test_phenobase:
    image: postgis/postgis:16-3.4
    container_name: phenobase_docker
    ports:
     - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d test_phenobase" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
volumes:
  pgdata: